Add missing ember-getowner-polyfill dependency
Otherwise following the README setup instructions fails with:

```
Error: Could not find module `ember-getowner-polyfill` imported from
`auth0-ember-simple-auth/authenticators/lock`
```